# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\root\my_life\sbme_2025\3rd_year\first_semester\DSP\tasks\task_4\task4\Signal_Blend_Pro\Mixer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1404, 795)
        MainWindow.setStyleSheet("background-color: #fafafa;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_img_1 = QtWidgets.QGraphicsView(self.groupBox)
        self.label_img_1.setMinimumSize(QtCore.QSize(200, 200))
        self.label_img_1.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.label_img_1.setObjectName("label_img_1")
        self.gridLayout.addWidget(self.label_img_1, 1, 0, 1, 1)
        self.FT_label_1 = QtWidgets.QGraphicsView(self.groupBox)
        self.FT_label_1.setMinimumSize(QtCore.QSize(200, 200))
        self.FT_label_1.setStyleSheet("QGraphicsView{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.FT_label_1.setObjectName("FT_label_1")
        self.gridLayout.addWidget(self.FT_label_1, 1, 1, 1, 1)
        self.FT_img1 = QtWidgets.QComboBox(self.groupBox)
        self.FT_img1.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(3, 3, 3); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}\n"
"\n"
"\n"
"\n"
"            \n"
"")
        self.FT_img1.setObjectName("FT_img1")
        self.FT_img1.addItem("")
        self.FT_img1.addItem("")
        self.FT_img1.addItem("")
        self.FT_img1.addItem("")
        self.FT_img1.addItem("")
        self.gridLayout.addWidget(self.FT_img1, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.FT_label_4 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.FT_label_4.setMinimumSize(QtCore.QSize(200, 200))
        self.FT_label_4.setStyleSheet("QGraphicsView{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.FT_label_4.setObjectName("FT_label_4")
        self.gridLayout_4.addWidget(self.FT_label_4, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_img_4 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.label_img_4.setMinimumSize(QtCore.QSize(200, 200))
        self.label_img_4.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.label_img_4.setObjectName("label_img_4")
        self.gridLayout_4.addWidget(self.label_img_4, 1, 0, 1, 1)
        self.FT_img4 = QtWidgets.QComboBox(self.groupBox_2)
        self.FT_img4.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(3, 3, 3); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}\n"
"\n"
"\n"
"\n"
"            \n"
"")
        self.FT_img4.setObjectName("FT_img4")
        self.FT_img4.addItem("")
        self.FT_img4.addItem("")
        self.FT_img4.addItem("")
        self.FT_img4.addItem("")
        self.FT_img4.addItem("")
        self.gridLayout_4.addWidget(self.FT_img4, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.FT_label_2 = QtWidgets.QGraphicsView(self.groupBox_5)
        self.FT_label_2.setMinimumSize(QtCore.QSize(200, 200))
        self.FT_label_2.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.FT_label_2.setObjectName("FT_label_2")
        self.gridLayout_6.addWidget(self.FT_label_2, 1, 1, 1, 1)
        self.label_img_2 = QtWidgets.QGraphicsView(self.groupBox_5)
        self.label_img_2.setMinimumSize(QtCore.QSize(200, 200))
        self.label_img_2.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.label_img_2.setObjectName("label_img_2")
        self.gridLayout_6.addWidget(self.label_img_2, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.FT_img2 = QtWidgets.QComboBox(self.groupBox_5)
        self.FT_img2.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(3, 3, 3); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}\n"
"\n"
"\n"
"\n"
"            \n"
"")
        self.FT_img2.setObjectName("FT_img2")
        self.FT_img2.addItem("")
        self.FT_img2.addItem("")
        self.FT_img2.addItem("")
        self.FT_img2.addItem("")
        self.FT_img2.addItem("")
        self.gridLayout_6.addWidget(self.FT_img2, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_img_3 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.label_img_3.setMinimumSize(QtCore.QSize(200, 200))
        self.label_img_3.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.label_img_3.setObjectName("label_img_3")
        self.gridLayout_8.addWidget(self.label_img_3, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)
        self.FT_label_3 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.FT_label_3.setMinimumSize(QtCore.QSize(200, 200))
        self.FT_label_3.setStyleSheet("QGraphicsView{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.FT_label_3.setObjectName("FT_label_3")
        self.gridLayout_8.addWidget(self.FT_label_3, 1, 1, 1, 1)
        self.FT_img3 = QtWidgets.QComboBox(self.groupBox_3)
        self.FT_img3.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(3, 3, 3); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}\n"
"\n"
"\n"
"\n"
"            \n"
"")
        self.FT_img3.setObjectName("FT_img3")
        self.FT_img3.addItem("")
        self.FT_img3.addItem("")
        self.FT_img3.addItem("")
        self.FT_img3.addItem("")
        self.FT_img3.addItem("")
        self.gridLayout_8.addWidget(self.FT_img3, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_8.setMaximumSize(QtCore.QSize(500, 1000))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.Image4 = QtWidgets.QLabel(self.groupBox_8)
        self.Image4.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Image4.setFont(font)
        self.Image4.setObjectName("Image4")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Image4)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.ft_img_slider4 = QtWidgets.QSlider(self.groupBox_8)
        self.ft_img_slider4.setMinimumSize(QtCore.QSize(300, 0))
        self.ft_img_slider4.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #3A3939;\n"
"    height: 11px;\n"
"    background: #201F1F;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.ft_img_slider4.setOrientation(QtCore.Qt.Horizontal)
        self.ft_img_slider4.setObjectName("ft_img_slider4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ft_img_slider4)
        self.Image_weight4 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Image_weight4.setFont(font)
        self.Image_weight4.setObjectName("Image_weight4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Image_weight4)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout_3)
        self.gridLayout_16.addLayout(self.formLayout_8, 7, 0, 1, 2)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.Image3 = QtWidgets.QLabel(self.groupBox_8)
        self.Image3.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Image3.setFont(font)
        self.Image3.setObjectName("Image3")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Image3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.ft_img_slider3 = QtWidgets.QSlider(self.groupBox_8)
        self.ft_img_slider3.setMinimumSize(QtCore.QSize(300, 0))
        self.ft_img_slider3.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #3A3939;\n"
"    height: 11px;\n"
"    background: #201F1F;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"")
        self.ft_img_slider3.setOrientation(QtCore.Qt.Horizontal)
        self.ft_img_slider3.setObjectName("ft_img_slider3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ft_img_slider3)
        self.Image_weight3 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Image_weight3.setFont(font)
        self.Image_weight3.setObjectName("Image_weight3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Image_weight3)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout_2)
        self.gridLayout_16.addLayout(self.formLayout_7, 5, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem, 9, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem1, 6, 1, 1, 1)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.Image2 = QtWidgets.QLabel(self.groupBox_8)
        self.Image2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Image2.setFont(font)
        self.Image2.setObjectName("Image2")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Image2)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.ft_img_slider2 = QtWidgets.QSlider(self.groupBox_8)
        self.ft_img_slider2.setMinimumSize(QtCore.QSize(300, 0))
        self.ft_img_slider2.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #3A3939;\n"
"    height: 11px;\n"
"    background: #201F1F;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"")
        self.ft_img_slider2.setOrientation(QtCore.Qt.Horizontal)
        self.ft_img_slider2.setObjectName("ft_img_slider2")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ft_img_slider2)
        self.Image_weight2 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Image_weight2.setFont(font)
        self.Image_weight2.setObjectName("Image_weight2")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Image_weight2)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout_9)
        self.gridLayout_16.addLayout(self.formLayout_6, 3, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem3, 4, 1, 1, 1)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.Image1 = QtWidgets.QLabel(self.groupBox_8)
        self.Image1.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Image1.setFont(font)
        self.Image1.setObjectName("Image1")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Image1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.ft_img_slider1 = QtWidgets.QSlider(self.groupBox_8)
        self.ft_img_slider1.setMinimumSize(QtCore.QSize(300, 0))
        self.ft_img_slider1.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #3A3939;\n"
"    height: 11px;\n"
"    background: #201F1F;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.ft_img_slider1.setOrientation(QtCore.Qt.Horizontal)
        self.ft_img_slider1.setObjectName("ft_img_slider1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ft_img_slider1)
        self.Image_weight1 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Image_weight1.setFont(font)
        self.Image_weight1.setObjectName("Image_weight1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Image_weight1)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout)
        self.gridLayout_16.addLayout(self.formLayout_5, 1, 0, 1, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        self.label_15.setMaximumSize(QtCore.QSize(6000, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.choose_output = QtWidgets.QComboBox(self.groupBox_8)
        self.choose_output.setMinimumSize(QtCore.QSize(0, 0))
        self.choose_output.setMaximumSize(QtCore.QSize(6000, 16777215))
        self.choose_output.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(3, 3, 3); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}\n"
"\n"
"\n"
"\n"
"            \n"
"")
        self.choose_output.setObjectName("choose_output")
        self.choose_output.addItem("")
        self.choose_output.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.choose_output)
        self.gridLayout_15.addLayout(self.formLayout_4, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem4, 4, 1, 1, 1)
        self.toggle_shading_button = QtWidgets.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Ubuntu,sans-serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.toggle_shading_button.setFont(font)
        self.toggle_shading_button.setAutoFillBackground(False)
        self.toggle_shading_button.setStyleSheet("QPushButton{\n"
"background-color: #54b4d3;\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"font-size: 100%;\n"
"height: 30px;\n"
"line-height: 1.15;\n"
"outline: none;\n"
"padding: 3 10px;\n"
"text-align: center;\n"
"width: 30px; /* Reduced width to 200 pixels */\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(58, 140, 164);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(41, 108, 130);\n"
"}\n"
"QPushButton:focus {\n"
"                    border-color: #3a8ca4;\n"
"                    color: #3a8ca4;\n"
"                    outline: none;\n"
"}\n"
"QPushButton.dark:hover {\n"
"                    background-color: #17222d; /* Adjust dark mode hover background color */\n"
"}\n"
"\n"
"                QPushButton.dark:pressed {\n"
"                    background-color: #0f1417; /* Adjust dark mode pressed background color */\n"
"}")
        self.toggle_shading_button.setFlat(False)
        self.toggle_shading_button.setObjectName("toggle_shading_button")
        self.gridLayout_15.addWidget(self.toggle_shading_button, 2, 0, 1, 1)
        self.rectangle_region_button = QtWidgets.QPushButton(self.groupBox_8)
        self.rectangle_region_button.setMinimumSize(QtCore.QSize(50, 0))
        self.rectangle_region_button.setMaximumSize(QtCore.QSize(6000, 16777215))
        font = QtGui.QFont()
        font.setFamily("-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Ubuntu,sans-serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rectangle_region_button.setFont(font)
        self.rectangle_region_button.setStyleSheet("QPushButton{\n"
"background-color: #54b4d3;\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"font-size: 100%;\n"
"height: 30px;\n"
"line-height: 1.15;\n"
"outline: none;\n"
"padding: 3 10px;\n"
"text-align: center;\n"
"width: 30px; /* Reduced width to 200 pixels */\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(58, 140, 164);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(41, 108, 130);\n"
"}\n"
"QPushButton:focus {\n"
"                    border-color: #3a8ca4;\n"
"                    color: #3a8ca4;\n"
"                    outline: none;\n"
"}\n"
"QPushButton.dark:hover {\n"
"                    background-color: #17222d; /* Adjust dark mode hover background color */\n"
"}\n"
"\n"
"                QPushButton.dark:pressed {\n"
"                    background-color: #0f1417; /* Adjust dark mode pressed background color */\n"
"}\n"
"")
        self.rectangle_region_button.setObjectName("rectangle_region_button")
        self.gridLayout_15.addWidget(self.rectangle_region_button, 0, 0, 1, 1)
        self.reset_region_button = QtWidgets.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Ubuntu,sans-serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.reset_region_button.setFont(font)
        self.reset_region_button.setStyleSheet("QPushButton{\n"
"background-color: #FF4742;\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"font-size: 100%;\n"
"height: 30px;\n"
"line-height: 1.15;\n"
"outline: none;\n"
"padding: 3 10px;\n"
"text-align: center;\n"
"width: 30px; /* Reduced width to 200 pixels */\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(225, 61, 58);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(180, 49, 47);\n"
"}")
        self.reset_region_button.setObjectName("reset_region_button")
        self.gridLayout_15.addWidget(self.reset_region_button, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem5, 4, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 2)
        self.gridLayout_14.addWidget(self.groupBox_8, 0, 1, 2, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.graphicsView_10 = QtWidgets.QGraphicsView(self.groupBox_6)
        self.graphicsView_10.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.gridLayout_9.addWidget(self.graphicsView_10, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.groupBox_7)
        self.graphicsView_9.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.gridLayout_10.addWidget(self.graphicsView_9, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1404, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Image 1"))
        self.label_11.setText(_translate("MainWindow", "             FT Component"))
        self.FT_img1.setItemText(0, _translate("MainWindow", "Select A Component..."))
        self.FT_img1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.FT_img1.setItemText(2, _translate("MainWindow", "Phase"))
        self.FT_img1.setItemText(3, _translate("MainWindow", "Real"))
        self.FT_img1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Image 4"))
        self.label_14.setText(_translate("MainWindow", "             FT Component"))
        self.FT_img4.setItemText(0, _translate("MainWindow", "Select A Component..."))
        self.FT_img4.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.FT_img4.setItemText(2, _translate("MainWindow", "Phase"))
        self.FT_img4.setItemText(3, _translate("MainWindow", "Real"))
        self.FT_img4.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Image 2"))
        self.label_13.setText(_translate("MainWindow", "             FT Component"))
        self.FT_img2.setItemText(0, _translate("MainWindow", "Select A Component..."))
        self.FT_img2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.FT_img2.setItemText(2, _translate("MainWindow", "Phase"))
        self.FT_img2.setItemText(3, _translate("MainWindow", "Real"))
        self.FT_img2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Image 3"))
        self.label_12.setText(_translate("MainWindow", "             FT Component"))
        self.FT_img3.setItemText(0, _translate("MainWindow", "Select A Component..."))
        self.FT_img3.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.FT_img3.setItemText(2, _translate("MainWindow", "Phase"))
        self.FT_img3.setItemText(3, _translate("MainWindow", "Real"))
        self.FT_img3.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.Image4.setText(_translate("MainWindow", "Image 4"))
        self.Image_weight4.setText(_translate("MainWindow", "0"))
        self.Image3.setText(_translate("MainWindow", "Image 3"))
        self.Image_weight3.setText(_translate("MainWindow", "0"))
        self.Image2.setText(_translate("MainWindow", "Image 2"))
        self.Image_weight2.setText(_translate("MainWindow", "0"))
        self.Image1.setText(_translate("MainWindow", "Image 1"))
        self.Image_weight1.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "Mixer Output to"))
        self.choose_output.setItemText(0, _translate("MainWindow", "Output 1"))
        self.choose_output.setItemText(1, _translate("MainWindow", "Output 2"))
        self.toggle_shading_button.setText(_translate("MainWindow", "Toggle Shading"))
        self.rectangle_region_button.setText(_translate("MainWindow", "Select Regions"))
        self.reset_region_button.setText(_translate("MainWindow", "Reset Regions"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Output 1"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Output 2"))
